### ISSUE TITLE
Toimituskulut lähetetään eteenpäin verottomana?

### ISSUE THREAD

**Issue by BrotherMouzone** [Paybyway/maksukaista_magento#1]
Redirect.phpssa shipping methodille määritellään vero 0% 'ITEM_TAX' => 0, kun taas tuoteriville haetaan veroprosenttii. 'ITEM_TAX' => (int)$item->getTaxPercent().

Kauppiaspaneeelissakin näkyy pkt verottomana:
Tuotteen tyyppi Toimituskulu 
Veroprosentti 	 	0 %

**Comment by kkarein** [comment]
Toimituskulutuoteriville päivitetty nyt veroprosentti ja veroton hinta.
